name: 'Create A Release Branch Weekly'
description: 'Create A Release Branch GitHub Action'
author: 'Ehsan Sarshar'
branding:
  icon: 'git-branch'
  color: 'green'
inputs:
  baseNumber:
    description: 'the number to start release with for example here baseNumber 3 `"release-3"`'
    default: '0'
  numberOfWeeks:
    description: 'create release branch on each number of weeks'
    default: '2'
  baseDate:
    description: 'base date to check if specific number of weeks are passed'
    required: true
outputs:
  created:
    description: 'Boolean value representing whether or not a new branch was created.'
runs:
  using: 'node12'
  main: 'dist/index.js'
